export { HeroSection } from './HeroSection'
export { AboutSection } from './AboutSection'
export { ServicesSection } from './ServicesSection'
export { GallerySection } from './GallerySection'
export { FaqSection } from './FaqSection'
export { ContactSection } from './ContactSection'
